# Generated by Django 3.2.8 on 2021-11-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dcsd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
